
name: Build Pitch Deck

on:
  push:
    branches: [main]
    paths:
      - 'pitch_deck/**'
      - '.github/workflows/deck.yml'

jobs:
  build-pitch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Marp CLI + Puppeteer
      run: |
        npm install @marp-team/marp-cli puppeteer

    - name: Check Marp CLI Availability
      run: |
        npx marp --version || echo "Marp CLI not available"

    - name: Build Deck from pitch_deck/
      run: |
        mkdir -p docs
        npx marp pitch_deck/slides.md \
          -o docs/index.html \
          --theme moon --html --highlight-theme solarized-light

    - name: Push Updated Deck to docs/
      run: |
        git config user.name "OrbitBot"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Auto-build deck from pitch_deck/"
        git push origin main || echo "Nothing to commit"
