name: Build Pitch Deck

on:
  push:
    branches: [main]
    paths:
      - 'pitch_deck/**'
      - '.github/workflows/deck.yml'

jobs:
  build-pitch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Marp CLI
      run: |
        npm install -g @marp-team/marp-cli

    - name: Build Deck
      run: |
        marp pitch_deck/slides.md -o docs/index.html \
          --theme moon --html --highlight-theme solarized-light

    - name: Push updated deck
      run: |
        git config user.name "OrbitBot"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Auto-build deck from pitch_deck/"
        git push origin main || echo "Nothing to commit"
